Config processing with lazy error handling
Graylog2/JadConfig pull request #127
Opened 2024-03-27 11:50 UTC by luk-kaminski

## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

2024-04-19 11:45 UTC, todvora commented
I have adapted the behaviour to match the eager processing mode. The lazy method now doesn't return any result, the return type is void. The outcome of the processing is either configured beans or an ValidationException, aggregating all the errors and providing access to the underlying ProcessingResponse, if the caller wants to handle the errors in a specific way.

This is how the exception looks now, aggregating three missing properties:
![image](https://github.com/Graylog2/JadConfig/assets/4102775/99396506-15eb-4652-82d6-ca919d2774ac)

The only change from the caller perspective is to switch from `jadConfig.process()` to `jadConfig.processFailingLazily()`. Everything else can stay as it is, with the same error handling in place as before.

2024-06-06 09:22 UTC, bernd requested changes

2024-06-06 09:22 UTC, bernd commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +import static com.github.joschi.jadconfig.ReflectionUtils.*;
Please remove the wildcard import.

2024-06-06 09:22 UTC, bernd commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +        ProcessingResponse response = new ProcessingResponse();
The `response` can be final.

2024-06-06 09:22 UTC, bernd commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +        Map<String, Exception> fieldProcessingProblems = new HashMap<>();
The field can be final.

2024-06-06 09:22 UTC, bernd commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +        Map<String, Exception> problems = new HashMap<>();
The field can be final.

2024-06-06 09:22 UTC, bernd commented on src/test/java/com/github/joschi/jadconfig/testbeans/ValidatedConfigurationBean.java
> +    public void myCustomValidatorMethod() throws ValidationException {
What's the reason for renaming this method?

2024-06-06 09:22 UTC, bernd commented on src/main/java/com/github/joschi/jadconfig/LazyValidationException.java
> +        // TODO: should we include class name of the bean or not?
Are these still open tasks?

2024-06-06 10:02 UTC, todvora commented on src/test/java/com/github/joschi/jadconfig/testbeans/ValidatedConfigurationBean.java
> +    public void myCustomValidatorMethod() throws ValidationException {
The name of the method is string-matched later in the test. "validate" seems like too vague name and it's not really clear where it is coming from. Changing the name to "myCustomValidatorMethod" makes the connection clear and and removes any doubts.

2024-06-06 10:17 UTC, todvora commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +        ProcessingResponse response = new ProcessingResponse();
rewritten this block to avoid all mutations of the ProcessingResponse.

2024-06-06 10:17 UTC, todvora commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +        Map<String, Exception> fieldProcessingProblems = new HashMap<>();
fixed

2024-06-06 10:17 UTC, todvora commented on src/main/java/com/github/joschi/jadconfig/JadConfig.java
> +        Map<String, Exception> problems = new HashMap<>();
fixed

2024-06-06 10:18 UTC, todvora commented on src/main/java/com/github/joschi/jadconfig/LazyValidationException.java
> +        // TODO: should we include class name of the bean or not?
no, removed the todo and simplified the code

2024-06-10 07:43 UTC, bernd commented on src/test/java/com/github/joschi/jadconfig/testbeans/ValidatedConfigurationBean.java
> +    public void myCustomValidatorMethod() throws ValidationException {
Okay, thanks. :+1:

2024-06-10 07:45 UTC, bernd approved these changes

2024-06-10 07:45 UTC, merged